-- =============================================================================
-- LM Admin Panel - Database tables (based on frontend UI)
-- Database: lms
-- Pages: Gallery (Banners), Offers (Coupons), Categories (Main/Sub/Child)
-- No soft delete | No unused columns
-- =============================================================================
-- Frontend field mapping:
--   Banners     -> title, image
--   Coupons     -> code, discount(value), start_date, expiry_date, status
--   Categories  -> name only (slug auto-generated by backend)
-- =============================================================================

USE lms;

-- =============================================================================
-- 1. BANNERS
-- =============================================================================

-- Fresh table (new project)
CREATE TABLE IF NOT EXISTS banners (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  image VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Upgrade existing table: run each line; skip if "Unknown column" error appears
-- ALTER TABLE banners DROP COLUMN subtitle;
-- ALTER TABLE banners DROP COLUMN description;
-- ALTER TABLE banners DROP COLUMN mobile_image;
-- ALTER TABLE banners DROP COLUMN type;
-- ALTER TABLE banners DROP COLUMN position;
-- ALTER TABLE banners DROP COLUMN link;
-- ALTER TABLE banners DROP COLUMN button_text;
-- ALTER TABLE banners DROP COLUMN button_link;
-- ALTER TABLE banners DROP COLUMN sort_order;
-- ALTER TABLE banners DROP COLUMN priority;
-- ALTER TABLE banners DROP COLUMN start_date;
-- ALTER TABLE banners DROP COLUMN end_date;
-- ALTER TABLE banners DROP COLUMN status;
-- ALTER TABLE banners DROP COLUMN deleted_at;

-- =============================================================================
-- 2. COUPONS
-- =============================================================================

CREATE TABLE IF NOT EXISTS coupons (
  id INT NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL,
  type ENUM('percentage', 'flat') NOT NULL DEFAULT 'percentage',
  value DECIMAL(10,2) NOT NULL,
  start_date DATE DEFAULT NULL,
  expiry_date DATE DEFAULT NULL,
  status ENUM('active', 'inactive', 'expired') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_coupons_code (code),
  KEY idx_coupons_status (status),
  KEY idx_coupons_expiry (expiry_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Upgrade existing table:
-- ALTER TABLE coupons DROP COLUMN minimum_order_amount;
-- ALTER TABLE coupons DROP COLUMN maximum_discount;
-- ALTER TABLE coupons DROP COLUMN usage_limit;
-- ALTER TABLE coupons DROP COLUMN used_count;
-- ALTER TABLE coupons DROP COLUMN per_user_limit;
-- ALTER TABLE coupons DROP COLUMN is_for_new_customers;
-- ALTER TABLE coupons DROP COLUMN description;
-- ALTER TABLE coupons DROP COLUMN deleted_at;
-- ALTER TABLE coupons MODIFY expiry_date DATE NULL;

-- =============================================================================
-- 3. MAIN CATEGORIES  (table: categories)
-- =============================================================================

CREATE TABLE IF NOT EXISTS categories (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_categories_slug (slug),
  KEY idx_categories_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Upgrade existing table:
-- ALTER TABLE categories DROP COLUMN description;
-- ALTER TABLE categories DROP COLUMN image;
-- ALTER TABLE categories DROP COLUMN icon;
-- ALTER TABLE categories DROP COLUMN status;
-- ALTER TABLE categories DROP COLUMN sort_order;
-- ALTER TABLE categories DROP COLUMN meta_title;
-- ALTER TABLE categories DROP COLUMN meta_description;
-- ALTER TABLE categories DROP COLUMN deleted_at;

-- =============================================================================
-- 4. SUB CATEGORIES
-- =============================================================================

CREATE TABLE IF NOT EXISTS sub_categories (
  id INT NOT NULL AUTO_INCREMENT,
  main_category_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sub_categories_main (main_category_id),
  KEY idx_sub_categories_slug (slug),
  CONSTRAINT fk_sub_categories_main
    FOREIGN KEY (main_category_id) REFERENCES categories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Upgrade existing table:
-- ALTER TABLE sub_categories DROP COLUMN description;
-- ALTER TABLE sub_categories DROP COLUMN image;
-- ALTER TABLE sub_categories DROP COLUMN status;
-- ALTER TABLE sub_categories DROP COLUMN sort_order;
-- ALTER TABLE sub_categories DROP COLUMN meta_title;
-- ALTER TABLE sub_categories DROP COLUMN meta_description;
-- ALTER TABLE sub_categories DROP COLUMN deleted_at;

-- =============================================================================
-- 5. CHILD CATEGORIES
-- =============================================================================

CREATE TABLE IF NOT EXISTS child_categories (
  id INT NOT NULL AUTO_INCREMENT,
  sub_category_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_child_categories_sub (sub_category_id),
  KEY idx_child_categories_slug (slug),
  CONSTRAINT fk_child_categories_sub
    FOREIGN KEY (sub_category_id) REFERENCES sub_categories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Upgrade existing table:
-- ALTER TABLE child_categories DROP COLUMN description;
-- ALTER TABLE child_categories DROP COLUMN image;
-- ALTER TABLE child_categories DROP COLUMN status;
-- ALTER TABLE child_categories DROP COLUMN sort_order;
-- ALTER TABLE child_categories DROP COLUMN meta_title;
-- ALTER TABLE child_categories DROP COLUMN meta_description;
-- ALTER TABLE child_categories DROP COLUMN deleted_at;
